### ISSUE TITLE
[NL] Address Format Issue

### ISSUE THREAD

**Issue by MircoBabin** [InterNACHI/franklin#1]
This issue is:

- [X] Minor: I can enter an address but it's not ideal

## Sample Address:

In the Netherlands the Postal code is always 4 digits + 2 uppercase-letters.

e.g. 5482kl, 5482KL, 5482 kl, 5482 KL are all the same postalcode.

## Issue:

1) When entering "5482kl" without a space between the digits and letters, a validation error arises. Very annoying, because the input could automatically be converted to the wanted format.

2) When entering "5482 kl" with a space between the digits and letters, still a validation error arises. Very annoying, because "kl" is lowercase and should automatically be converted to uppercase.

3) When entering " 5482 KL" (with a leading space), a validation error arises. Very annoying, because the postalcode field should be trimmed.

4) When entering "5482 KL " (with a trailing space), a validation error arises. Very annoying, because the postalcode field should be trimmed.

![image](https://user-images.githubusercontent.com/8981285/113419381-a3c05d00-93c7-11eb-9219-37bf86607013.png)

**Comment by inxilpro** [comment]
Thanks for reporting this!

This [should be fixed](https://internachi.github.io/franklin/?address=%7B%22country%22%3A%22NL%22%2C%22address1%22%3A%22Address%22%2C%22address2%22%3A%22%22%2C%22administrative_area%22%3A%22%22%2C%22locality%22%3A%22City%22%2C%22sublocality%22%3A%22%22%2C%22postal_code%22%3A%225482kl%22%2C%22sorting_code%22%3A%22%22%7D) with v0.5.0. Can you check to make sure?

**Comment by MircoBabin** [comment]
Tested and all issues are corrrected.

As a sidenote, but I don't know if this is in the scope of this project. It would be great if the postalcode in the JSON at the bottom of the page would be normalized. When "5482kl" is entered, it would be nice if this was presented via the JSON as "5482 KL".

**Comment by inxilpro** [comment]
We plan on eventually offering a server-side companion package that would help round out the functionality without adding more weight to the client side script. I've worked really hard to keep the JS code as small as possible, because the library is inherently larger due to all the country definitions.

So things like normalization and more involved validation would probably end up in that library, if we ever implement them.
