### ISSUE TITLE
[JE] Address Format Issue

### ISSUE THREAD

**Issue by PhilETaylor** [InterNACHI/franklin#6]
This issue is:

- [ ] Major: I cannot enter an address using Franklin
- [X] Minor: I can enter an address but it's not ideal

## Sample Address:

Lots of examples in the government A-Z contacts https://www.gov.je/pages/contacts.aspx?contactId=700
```
19-21 Broad Street
St Helier
Jersey
JE2 3RR

or

3 Belgreve Terrace
Dicq Road
St Saviour
Jersey
JE2 7PD

```

Obviously `Jersey` is often omitted as it's the island name and assumed locally. 

## Issue:

The Island of [Jersey, Channel Islands](https://en.wikipedia.org/wiki/Jersey), has no Cities. 

We have 12 [Parishes](https://en.wikipedia.org/wiki/Parishes_of_Jersey) (which are *really* important to the locals, apparently). A Parish would probably be considered an `administrative_area`

- Remove City - not applicable.
- Possibly add 12 parishes as a dropdown selector?
- Autodetect gave United States

**Comment by inxilpro** [comment]
So it looks like based on the [Google data source](https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/JE), the parish is considered a locality (not administrative area). I think the best solution is to use the label "Parish" for the locality field. What do you think about that?

**Comment by inxilpro** [comment]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/21592/235515464-257563de-6ad6-49c5-9ea9-1e367e9fbeae.png">

This would be the updated form.

**Comment by PhilETaylor** [comment]
Yup that would work

"Administrative" can have multiple meanings I guess - but I think in this respect you are correct. 

The locals are very protective of their parishes haha

**Comment by inxilpro** [comment]
Perfect. I'll include this change in the next release! Thanks :)
