### ISSUE TITLE
[GB] Address Format Issue

### ISSUE THREAD

**Issue by PhilETaylor** [InterNACHI/franklin#7]
This issue is:

- [ ] Major: I cannot enter an address using Franklin
- [X] Minor: I can enter an address but it's not ideal

## Sample Address:

```
Mrs Smith 
71 Cherry Court 
SOUTHAMPTON 
SO53 5PD
```

## Issue:

Your form has "Postal" instead of what people from the UK would call a "Post Code". In the example "SO53 5PD" is a post code.

**Comment by inxilpro** [comment]
Got it! Should be fixed in an upcoming release.
